services:
  # AGENTE - Responsável pela comunicação com o Docker
  portainer-agent:
    image: portainer/agent:2.33.7
    container_name: portainer-agent
    hostname: portainer-agent
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/docker/volumes:/var/lib/docker/volumes
      - /:/host
      # Volume para armazenar certificados (necessário para o agente)
      - agent_data:/data
    networks:
      portainer_network:
        ipv4_address: 172.99.0.10
    # Configurações de segurança AJUSTADAS
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - DAC_OVERRIDE
      - NET_BIND_SERVICE  # Necessário para bind de porta
    # Removido read_only: true temporariamente para teste
    # read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    command: ["--http-enabled"]  # Forçar HTTP
    

  # PORTAINER APP - Interface web
  portainer-app:
    image: portainer/portainer-ce:latest
    container_name: portainer-app
    hostname: portainer-app
    restart: unless-stopped
    user: "203:203"
    command: -H tcp://172.99.0.10:9001 --tlsskipverify
    ports:
      - "8999:9000"
      - "9443:9443"
    volumes:
      - app_data:/data
    security_opt:
      - no-new-privileges:true
    depends_on:
      - portainer-agent
    networks:
      portainer_network:
        ipv4_address: 172.99.0.11

volumes:
  app_data:
  agent_data:

networks:
  portainer_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.99.0.0/16
          gateway: 172.99.0.1